---
name: Notify imgproxy/imgproxy-helm on updated 'configuration' part of the docs
on:
  push:
    branches:
      - master
    paths:
      - docs/configuration/**.mdx
jobs:
  notify-imgproxy-helm:
    runs-on: ubuntu-latest
    steps:
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.WORKFLOW_DISPATCH_TOKEN }}
          repository: imgproxy/imgproxy-helm
          event-type: imgproxy-config-updated
          client-payload: '{"actor":"${{ github.actor }}","link":"${{ github.event.compare }}"}'
