---
name: Notify imgproxy/imgproxy-js-core on updated 'usage' part of the docs
on:
  push:
    branches:
      - master
    paths:
      - docs/usage/**.mdx
jobs:
  notify-imgproxy-helm:
    runs-on: ubuntu-latest
    steps:
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.WORKFLOW_DISPATCH_TOKEN }}
          repository: imgproxy/imgproxy-js-core
          event-type: imgproxy-usage-updated
          client-payload: '{"actor":"${{ github.actor }}","link":"${{ github.event.compare }}"}'
